package yzhao.blog.bean;

import java.util.Date;

public class AdminLoginLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_login_log.id
     *
     * @mbg.generated Fri Jun 08 23:54:49 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_login_log.admin_id
     *
     * @mbg.generated Fri Jun 08 23:54:49 CST 2018
     */
    private Integer adminId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_login_log.date
     *
     * @mbg.generated Fri Jun 08 23:54:49 CST 2018
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_login_log.ip
     *
     * @mbg.generated Fri Jun 08 23:54:49 CST 2018
     */
    private String ip;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_login_log.id
     *
     * @return the value of admin_login_log.id
     *
     * @mbg.generated Fri Jun 08 23:54:49 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_login_log.id
     *
     * @param id the value for admin_login_log.id
     *
     * @mbg.generated Fri Jun 08 23:54:49 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_login_log.admin_id
     *
     * @return the value of admin_login_log.admin_id
     *
     * @mbg.generated Fri Jun 08 23:54:49 CST 2018
     */
    public Integer getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_login_log.admin_id
     *
     * @param adminId the value for admin_login_log.admin_id
     *
     * @mbg.generated Fri Jun 08 23:54:49 CST 2018
     */
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_login_log.date
     *
     * @return the value of admin_login_log.date
     *
     * @mbg.generated Fri Jun 08 23:54:49 CST 2018
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_login_log.date
     *
     * @param date the value for admin_login_log.date
     *
     * @mbg.generated Fri Jun 08 23:54:49 CST 2018
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_login_log.ip
     *
     * @return the value of admin_login_log.ip
     *
     * @mbg.generated Fri Jun 08 23:54:49 CST 2018
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_login_log.ip
     *
     * @param ip the value for admin_login_log.ip
     *
     * @mbg.generated Fri Jun 08 23:54:49 CST 2018
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }
}