package yzhao.blog.bean;

import java.util.Date;

public class Article {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.id
     *
     * @mbg.generated Fri Jun 08 23:54:49 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.title
     *
     * @mbg.generated Fri Jun 08 23:54:49 CST 2018
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.keywords
     *
     * @mbg.generated Fri Jun 08 23:54:49 CST 2018
     */
    private String keywords;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.desci
     *
     * @mbg.generated Fri Jun 08 23:54:49 CST 2018
     */
    private String desci;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.pic
     *
     * @mbg.generated Fri Jun 08 23:54:49 CST 2018
     */
    private String pic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.click
     *
     * @mbg.generated Fri Jun 08 23:54:49 CST 2018
     */
    private Integer click;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.time
     *
     * @mbg.generated Fri Jun 08 23:54:49 CST 2018
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.catalog_id
     *
     * @mbg.generated Fri Jun 08 23:54:49 CST 2018
     */
    private Integer catalogId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.content
     *
     * @mbg.generated Fri Jun 08 23:54:49 CST 2018
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.id
     *
     * @return the value of article.id
     *
     * @mbg.generated Fri Jun 08 23:54:49 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.id
     *
     * @param id the value for article.id
     *
     * @mbg.generated Fri Jun 08 23:54:49 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.title
     *
     * @return the value of article.title
     *
     * @mbg.generated Fri Jun 08 23:54:49 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.title
     *
     * @param title the value for article.title
     *
     * @mbg.generated Fri Jun 08 23:54:49 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.keywords
     *
     * @return the value of article.keywords
     *
     * @mbg.generated Fri Jun 08 23:54:49 CST 2018
     */
    public String getKeywords() {
        return keywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.keywords
     *
     * @param keywords the value for article.keywords
     *
     * @mbg.generated Fri Jun 08 23:54:49 CST 2018
     */
    public void setKeywords(String keywords) {
        this.keywords = keywords == null ? null : keywords.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.desci
     *
     * @return the value of article.desci
     *
     * @mbg.generated Fri Jun 08 23:54:49 CST 2018
     */
    public String getDesci() {
        return desci;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.desci
     *
     * @param desci the value for article.desci
     *
     * @mbg.generated Fri Jun 08 23:54:49 CST 2018
     */
    public void setDesci(String desci) {
        this.desci = desci == null ? null : desci.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.pic
     *
     * @return the value of article.pic
     *
     * @mbg.generated Fri Jun 08 23:54:49 CST 2018
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.pic
     *
     * @param pic the value for article.pic
     *
     * @mbg.generated Fri Jun 08 23:54:49 CST 2018
     */
    public void setPic(String pic) {
        this.pic = pic == null ? null : pic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.click
     *
     * @return the value of article.click
     *
     * @mbg.generated Fri Jun 08 23:54:49 CST 2018
     */
    public Integer getClick() {
        return click;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.click
     *
     * @param click the value for article.click
     *
     * @mbg.generated Fri Jun 08 23:54:49 CST 2018
     */
    public void setClick(Integer click) {
        this.click = click;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.time
     *
     * @return the value of article.time
     *
     * @mbg.generated Fri Jun 08 23:54:49 CST 2018
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.time
     *
     * @param time the value for article.time
     *
     * @mbg.generated Fri Jun 08 23:54:49 CST 2018
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.catalog_id
     *
     * @return the value of article.catalog_id
     *
     * @mbg.generated Fri Jun 08 23:54:49 CST 2018
     */
    public Integer getCatalogId() {
        return catalogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.catalog_id
     *
     * @param catalogId the value for article.catalog_id
     *
     * @mbg.generated Fri Jun 08 23:54:49 CST 2018
     */
    public void setCatalogId(Integer catalogId) {
        this.catalogId = catalogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.content
     *
     * @return the value of article.content
     *
     * @mbg.generated Fri Jun 08 23:54:49 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.content
     *
     * @param content the value for article.content
     *
     * @mbg.generated Fri Jun 08 23:54:49 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}