package yzhao.blog.bean;

public class Catalog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column catalog.id
     *
     * @mbg.generated Fri Jun 08 23:54:49 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column catalog.name
     *
     * @mbg.generated Fri Jun 08 23:54:49 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column catalog.keywords
     *
     * @mbg.generated Fri Jun 08 23:54:49 CST 2018
     */
    private String keywords;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column catalog.type
     *
     * @mbg.generated Fri Jun 08 23:54:49 CST 2018
     */
    private byte[] type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column catalog.desc
     *
     * @mbg.generated Fri Jun 08 23:54:49 CST 2018
     */
    private String desc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column catalog.id
     *
     * @return the value of catalog.id
     *
     * @mbg.generated Fri Jun 08 23:54:49 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column catalog.id
     *
     * @param id the value for catalog.id
     *
     * @mbg.generated Fri Jun 08 23:54:49 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column catalog.name
     *
     * @return the value of catalog.name
     *
     * @mbg.generated Fri Jun 08 23:54:49 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column catalog.name
     *
     * @param name the value for catalog.name
     *
     * @mbg.generated Fri Jun 08 23:54:49 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column catalog.keywords
     *
     * @return the value of catalog.keywords
     *
     * @mbg.generated Fri Jun 08 23:54:49 CST 2018
     */
    public String getKeywords() {
        return keywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column catalog.keywords
     *
     * @param keywords the value for catalog.keywords
     *
     * @mbg.generated Fri Jun 08 23:54:49 CST 2018
     */
    public void setKeywords(String keywords) {
        this.keywords = keywords == null ? null : keywords.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column catalog.type
     *
     * @return the value of catalog.type
     *
     * @mbg.generated Fri Jun 08 23:54:49 CST 2018
     */
    public byte[] getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column catalog.type
     *
     * @param type the value for catalog.type
     *
     * @mbg.generated Fri Jun 08 23:54:49 CST 2018
     */
    public void setType(byte[] type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column catalog.desc
     *
     * @return the value of catalog.desc
     *
     * @mbg.generated Fri Jun 08 23:54:49 CST 2018
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column catalog.desc
     *
     * @param desc the value for catalog.desc
     *
     * @mbg.generated Fri Jun 08 23:54:49 CST 2018
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }
}