package yzhao.blog.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;
import yzhao.blog.bean.AdminLoginLog;
import yzhao.blog.bean.AdminLoginLogExample;

@Repository
public interface AdminLoginLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_login_log
     *
     * @mbg.generated Fri Jun 08 23:54:49 CST 2018
     */
    long countByExample(AdminLoginLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_login_log
     *
     * @mbg.generated Fri Jun 08 23:54:49 CST 2018
     */
    int deleteByExample(AdminLoginLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_login_log
     *
     * @mbg.generated Fri Jun 08 23:54:49 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_login_log
     *
     * @mbg.generated Fri Jun 08 23:54:49 CST 2018
     */
    int insert(AdminLoginLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_login_log
     *
     * @mbg.generated Fri Jun 08 23:54:49 CST 2018
     */
    int insertSelective(AdminLoginLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_login_log
     *
     * @mbg.generated Fri Jun 08 23:54:49 CST 2018
     */
    List<AdminLoginLog> selectByExample(AdminLoginLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_login_log
     *
     * @mbg.generated Fri Jun 08 23:54:49 CST 2018
     */
    AdminLoginLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_login_log
     *
     * @mbg.generated Fri Jun 08 23:54:49 CST 2018
     */
    int updateByExampleSelective(@Param("record") AdminLoginLog record, @Param("example") AdminLoginLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_login_log
     *
     * @mbg.generated Fri Jun 08 23:54:49 CST 2018
     */
    int updateByExample(@Param("record") AdminLoginLog record, @Param("example") AdminLoginLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_login_log
     *
     * @mbg.generated Fri Jun 08 23:54:49 CST 2018
     */
    int updateByPrimaryKeySelective(AdminLoginLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_login_log
     *
     * @mbg.generated Fri Jun 08 23:54:49 CST 2018
     */
    int updateByPrimaryKey(AdminLoginLog record);


    /**
     * Add some custom method which needed
     * 1. List<AdminLoginLog> queryAll()
     * 2. List<AdminLoginLog> selectRencent(Integer adminId)
     * 3. int selectCountByAdminId(Integer adminId)
     */

    List<AdminLoginLog> queryAll();

    List<AdminLoginLog> selectRencent(Integer adminId);

    int selectCountByAdminId(Integer adminId);
}