package yzhao.blog.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;
import yzhao.blog.bean.Catalog;
import yzhao.blog.bean.CatalogExample;

@Repository
public interface CatalogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catalog
     *
     * @mbg.generated Fri Jun 08 23:54:49 CST 2018
     */
    long countByExample(CatalogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catalog
     *
     * @mbg.generated Fri Jun 08 23:54:49 CST 2018
     */
    int deleteByExample(CatalogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catalog
     *
     * @mbg.generated Fri Jun 08 23:54:49 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catalog
     *
     * @mbg.generated Fri Jun 08 23:54:49 CST 2018
     */
    int insert(Catalog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catalog
     *
     * @mbg.generated Fri Jun 08 23:54:49 CST 2018
     */
    int insertSelective(Catalog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catalog
     *
     * @mbg.generated Fri Jun 08 23:54:49 CST 2018
     */
    List<Catalog> selectByExampleWithBLOBs(CatalogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catalog
     *
     * @mbg.generated Fri Jun 08 23:54:49 CST 2018
     */
    List<Catalog> selectByExample(CatalogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catalog
     *
     * @mbg.generated Fri Jun 08 23:54:49 CST 2018
     */
    Catalog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catalog
     *
     * @mbg.generated Fri Jun 08 23:54:49 CST 2018
     */
    int updateByExampleSelective(@Param("record") Catalog record, @Param("example") CatalogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catalog
     *
     * @mbg.generated Fri Jun 08 23:54:49 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") Catalog record, @Param("example") CatalogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catalog
     *
     * @mbg.generated Fri Jun 08 23:54:49 CST 2018
     */
    int updateByExample(@Param("record") Catalog record, @Param("example") CatalogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catalog
     *
     * @mbg.generated Fri Jun 08 23:54:49 CST 2018
     */
    int updateByPrimaryKeySelective(Catalog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catalog
     *
     * @mbg.generated Fri Jun 08 23:54:49 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(Catalog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catalog
     *
     * @mbg.generated Fri Jun 08 23:54:49 CST 2018
     */
    int updateByPrimaryKey(Catalog record);
}